services:
  kurosearch:
    container_name: 'kurosearch'
    restart: unless-stopped
    image: 'ghcr.io/flurbudurbur/kurosearch:latest'
    ports:
      - '443:443'
    cap_add:
      - 'NET_ADMIN'
    volumes:
      - data:/data
      - config:/config
    env_file:
      - '.env'

volumes:
  data:
  config:
